// src/design-tokens.ts

export const designTokens = {
  colors: {
    border: {
      brandAccent: "#0071e3",
      default: "#86868b",
      error: "#e30000",
      focus: "#0071e3",
      muted: "#e8e8ed",
      strong: "#1d1d1f",
      success: "#008009",
      warning: "#ffe045",
    },
    fill: {
      error: "#fff2f4",
      elevation: "#fff",
      primary: "#fff",
      secondary: "#fbfbfd",
      secondarySelected: "#e8e8ed",
      success: "#f5fff6",
      tertiary: "#f5f5f7",
      warning: "#fffef2",
    },
    glyph: {
      default: "#1d1d1f",
      error: "#e30000",
      muted: "#6e6e73",
      success: "#008009",
      warning: "#977009",
    },
  },
  spacing: {
    xxxxs: "2px",
    xxxs: "4px",
    xxs: "8px",
    xs: "12px",
    s: "16px",
    m: "20px",
    l: "24px",
    xl: "32px",
    xxl: "48px",
    xxxl: "64px",
    xxxxl: "72px",
  },
  typography: {
    h1: {
      fontFamily: "SF Pro Display",
      fontWeight: 600,
      fontSize: "64px",
      lineHeight: "64px",
      letterSpacing: "-0.1px",
    },
    h2: {
      fontFamily: "SF Pro Display",
      fontWeight: 600,
      fontSize: "48px",
      lineHeight: "48px",
      letterSpacing: "-0.1px",
    },
    title1: {
      fontFamily: "SF Pro Display",
      fontWeight: 400,
      fontSize: "40px",
      lineHeight: "40px",
      letterSpacing: "-0.1px",
    },
    title2: {
      fontFamily: "SF Pro Display",
      fontWeight: 400,
      fontSize: "28px",
      lineHeight: "32px",
      letterSpacing: "0",
    },
    title3: {
      fontFamily: "SF Pro Display",
      fontWeight: 400,
      fontSize: "20px",
      lineHeight: "24px",
      letterSpacing: "0",
    },
    bodyLarge: {
      fontFamily: "SF Pro Display",
      fontWeight: 400,
      fontSize: "20px",
      lineHeight: "24px",
      letterSpacing: "0.2px",
    },
    body: {
      fontFamily: "SF Pro Text",
      fontWeight: 400,
      fontSize: "16px",
      lineHeight: "20px",
      letterSpacing: "-0.3px",
    },
    bodySmall: {
      fontFamily: "SF Pro Text",
      fontWeight: 400,
      fontSize: "14px",
      lineHeight: "20px",
      letterSpacing: "-0.3px",
    },
    micro: {
      fontFamily: "SF Pro Text",
      fontWeight: 400,
      fontSize: "12px",
      lineHeight: "16px",
      letterSpacing: "-0.3px",
    },
  },
  border: {
    radius: {
      sharp: "0",
      circle: "100%",
      roundXsm: "4px",
      roundSm: "8px",
      roundMd: "12px",
      roundLg: "16px",
      roundXl: "24px",
    },
    width: {
      0: "0",
      1: "1px",
      2: "2px",
    },
  },
  shadows: {
    baseline: "0 0 0 0 #0000",
    raised: ["0 2px 4px 0 #0000001f", "0 2px 12px 0 #00000014"],
    elevated: ["0 2px 8px 0 #0000001f", "0 2px 16px 0 #00000014"],
    floating: ["0 2px 8px 0 #0000001f", "0 2px 24px 0 #00000014"],
  },
};
